# Assignment 11-part1: Neural Networks and PyTorch

This assignment is the continuation of the last week assignment and includes implementation of packpropagation from scratch, and also implementation of feedforward neural networks in PyTorch.



Only use the already imported library `numpy` and the Python standard library. For the evaluation you may also use scikit-learn (`sklearn`) and `matplotlib`. Make sure that the dataset `airfoil_self_noise.csv` is in the same directory as the notebook.

List your team members (name and immatriculation number) and indicate whether you are a B.Sc. Data Science or other group in the following cell:

- *Your names here*

In [ ]:
from typing import List

import matplotlib.pyplot as plt
import numpy as np

def load_dataset(path):
    from sklearn.model_selection import train_test_split

    data = np.genfromtxt(path)
    X, y = data[:, :5], data[:, 5]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2020)

    return X_train, X_test, y_train, y_test


X_train, X_test, y_train, y_test = load_dataset('airfoil_self_noise.csv')

## Task 3: Implementing a Feedforward Neural Network

In this task, you will implement a feedforward neural network for regression. The hyperparameters of the model are:
- `input_dim`: The dimension of the input vector.
- `output_dim`: The dimension of the output vector.
- `width`: The dimension of each hidden layer.
- `depth`: The number of hidden layers. For B.Sc. Data Science students, this parameter is constant with a value of 1.
- `learning_rate`: The learning rate for gradient descent.
- `epochs`: The number of epochs/iterations performed during training.

B.Sc. Data Science only have to implement for a single hidden layer, i.e. `depth = 1`. All other students have to implement the network for any `depth >= 1`.

The activation function for each hidden layer is ReLU ($g(x) = max(0, x)$). The output layer uses the identity as activation, since our objective is regression.

You have to implement the `FeedforwardNeuralNetworkRegressor`.

The `__init__` method initializes the network.
Initialize each weight and bias randomly with a standard Gaussian distribution using the numpy function `numpy.random.normal` with default parameters.

The `fit` method trains the network.
Use backpropagation with gradient descent similar to Task 2.
Use the whole training data set for each training epoch.
Use the mean squared error as loss function.

The `predict` method computes the forward-pass of the network.

We have provided code for preprocessing and validating your model.

In [ ]:
class FeedforwardNeuralNetworkRegressor(object):
    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_dims: List[int],
        depth: int,
        learning_rate: float,
        epochs: int
    ):
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.hidden_dims = hidden_dims
        self.depth = depth
        self.learning_rate = learning_rate
        self.epochs = epochs
        # Create list for all weights and biases
        # Create a randomly initizalized weight and bias matrix for the input layer


        # Create a randomly initizalized weight and bias matrix for each hidden layer



        # Create a randomly initizalized weight and bias matrix for the output layer




    def fit(self, X, y):
        errors = np.zeros(self.epochs)
        current_ep = self.epochs-1
        # Add training process
        for ep in range(self.epochs):



        return errors[:current_ep+1]

    def predict(self, X):
        # Run the forward pass and return the predicted output
        _, _, pred = self.forward(X)
        return pred


    def relu(self, layer):
        return np.maximum(0, layer)

    def relu_der(self, layer):
        return 1*(layer > 0)

    def mse_loss(self, y_pred, y_true):
        return np.mean((y_pred - y_true)*(y_pred - y_true))

    def mse_loss_der(self, y_pred, y_true):
        return 2 * (y_pred - y_true)

    def forward(self, X):
        # Implementation of the forward pass
        # Store the intermediate results of the hidden layers for the back propagation
        hidden_x = [X]
        hidden_z = []


        return hidden_z, hidden_x, output

    def backward(self, pred, y):
        # delta = intermediate loss derivatives


        return biases_der, weights_der


In [ ]:
y_train = y_train.reshape((-1, 1))
y_test = y_test.reshape((-1, 1))

def normalizeData(data, minData, maxData):
    return (data - minData)/(maxData - minData)

Xmin = X_train.min(axis=0)
Xmax = X_train.max(axis=0)
Ymin = y_train.min(axis=0)
Ymax = y_train.max(axis=0)

X_train = normalizeData(X_train, Xmin, Xmax)
X_test = normalizeData(X_test, Xmin, Xmax)
y_train = normalizeData(y_train, Ymin, Ymax)
y_test = normalizeData(y_test, Ymin, Ymax)

In [ ]:
def mse_loss(y_pred, y_true):
    return np.mean((y_pred - y_true)*(y_pred - y_true))


np.random.seed(2023)

input_dim = X_train.shape[1]
output_dim = y_train.shape[1]
nn = FeedforwardNeuralNetworkRegressor(input_dim, output_dim, [5], 1, 0.1, 100)
train_error = nn.fit(X_train, y_train)
print("Final training error ( Epoch", len(train_error), "):", train_error[len(train_error)-1])

y_pred = nn.predict(X_test)
test_error = mse_loss(y_pred, y_test)
print("Test error:", test_error)

plt.figure()
plt.plot(train_error)
plt.show()

## PyTorch:
In this part of the assignment, you will implement deep learning at the example of classification and regression tasks with PyTorch.
You are free to use any packages from the standard library and third-party libraries. However, to solve the assignment you will only need numpy, matplotlib, torch, and torchvision.

The following are covered in the rest of this assignment:


1.   Installation
2.   Tensor
3.   Autograd
4.   Building a model
5.   Training models


## Installation

Go to [PyTorch/Get Started](https://pytorch.org/get-started/locally/) to find installation instructions for torch and torchvisio for your specific hardware, operating system, and Python environment. If you are unsure about your hardware, select CPU as Compute Platform.

For example, installing for Windows via pip on CPU requires the following command:
```shell
pip3 install torch torchvision torchaudio
```

You might need to adjust some code in the following tasks, if you want to run it on a GPU.



At the first step, torch and its neural networks module, i.e., torch.nn should be imported.

In [ ]:
import torch
from torch import nn
from torch import optim
from torch.utils import data
import matplotlib.pyplot as plt
import numpy as np

# Tensors

Torch operates on `torch.Tensors`. These tensors are very similar to Numpy's n-dimensional arrays. Most operations you know from numpy, such as slicing, arithmetics, etc. work similarly with tensors. Note that you have to use the torch equivalents of methods such as sum and mean, since Torch can only support autodifferentiation with such methods. Arithmetic operations between tensors  and slicing automatically support autodifferentiation.

Here there are a few basic tensor manipulations.

In [ ]:
x = torch.tensor([[1, 4], [2,3]])
print('x = ', x)
print('type =' , x.dtype)

x = x.to(torch.float32)

print('\n x = ', x)
print('type =' , x.dtype)

y = torch.tensor([[1.0, 4.0], [2.0, 3.0]])

print('\n y = ', y)
print('type =' , y.dtype)

# Tensor with random values

z = torch.rand(2, 2)
print('\n A random tensor:')
print(z)

# Basic arithmatic operations
k1 = y + x
k2 = y * x
k3 = y @ x

print('\n Addition and Multiplication:')
print(k1, '\n', k2, '\n', k3)

x =  tensor([[1, 4],
        [2, 3]])
type = torch.int64

 x =  tensor([[1., 4.],
        [2., 3.]])
type = torch.float32

 y =  tensor([[1., 4.],
        [2., 3.]])
type = torch.float32

 A random tensor:
tensor([[0.1560, 0.9761],
        [0.2683, 0.1891]])

 Addition and Multiplication:
tensor([[2., 8.],
        [4., 6.]]) 
 tensor([[ 1., 16.],
        [ 4.,  9.]]) 
 tensor([[ 9., 16.],
        [ 8., 17.]])


# Autograd:
PyTorch includes automated differentiation engine. To allow differantionation of a function f(w) w.r.t. the tensor w, the tensor should have "requires_grad= True", e.g., w = torch.tensor([[0.2, 0.4],[0.8, 0.1],[2.0, 0.5]], requires_grad= True). You can access the gradient by w.grad.

##Task 4: Implementation of simple Feedforward Neural Network in Pytorch:

In the "Neural Networks Example" task described in the PDF file, you manually performed the forward pass and gradient calculation. Now, in this new task, you will implement the same task but using tensors and PyTorch's autograd functionality. Once you compute the loss, you can use the loss.backward() function to perform backpropagation. Your goal is to compare the results of the forward pass, loss calculation, backpropagation, and parameter updates between these two approaches (manual gradient computation v.s. automated gradient computation).

In [ ]:
# Define weights and biases



# Implement Forward pass



y = -1

# Compute loss and take automated differentiation


# Print the results (forward pass, gradients, etc.) and compare with the results you obtained manually in "Neural Network Example" in PDF file.


# Building a model:

PyTorch provided various building blocks of Neural Neuworks such as linear model, various activation functions (relu, tanh, etc), convolution layer, etc.    
## Modules

Modules are the second key component of Torch after tensors. Modules represent network layers, loss functions, and entire neural networks. Torch offers a large library of modules, which you can overview [here](https://pytorch.org/docs/stable/nn.html).

A [`torch.nn.Module`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html) can be easily implemented by inherting from `nn.Module` and implementing at least the `forward` method, which defines the computation your network makes during the forward pass. Due to Torch's autodifferentiation, the backward pass (including gradient computation) is performed automatically by Torch.

The following cell implements an example Module for a simple linear model with quadratic features.

In [ ]:
linear = nn.Linear(2,3) #w x + b

print("Initial weights:")
print(linear.weight)
print("\nInitial biases:")
print(linear.bias)

linear.bias = nn.Parameter(torch.tensor([1.0,2.0,3.0]))
print("\n Biases after setting:")
print(linear.bias)

h1 = linear(x.t())
print(h1)


Initial weights:
Parameter containing:
tensor([[-0.6144,  0.1389],
        [ 0.3795,  0.2146],
        [-0.4978, -0.2421]], requires_grad=True)

Initial biases:
Parameter containing:
tensor([ 0.0853, -0.5194, -0.7014], requires_grad=True)

 Biases after setting:
Parameter containing:
tensor([1., 2., 3.], requires_grad=True)
tensor([[0.6634, 2.8087, 2.0180]], grad_fn=<AddmmBackward0>)


##Task 5: Build a simple model in PyTorch:

In task 4, you implemented a simple neural network (introduced in PDF file, the part "neural network example") by using tensor. In this task, you will implement the neural network of task 4 by using torch.nn.Linear and asnwer the same questions given in the task "Neural Network example" in pdf file, and compare the results.

In [ ]:
import torch.optim as optim
class SimpleNN(nn.Module):

    def __init__(self):
        super(SimpleNN, self).__init__()
        # NN with one hidden layer (with 3 hidden nodes), and one output node
        # The input data is 2 dimensional

    # define forward pass
    def forward(self, x):

        return out

x = torch.tensor([1.0, 2.0])
neural_net = SimpleNN()
yhat = neural_net.forward(x)
y = -1

print('yhat = ', yhat)

# define loss function

loss =

print('loss = ', loss)


optimizer = optim.SGD(neural_net.parameters(), lr=0.1)
optimizer.zero_grad()

# Perform backward and NN parameters update by using backward and step functions

# Print the results (forward pass, gradients, etc.) and compare with the results of task 4


## Task 6: Implementing a Feedforward Neural Network with PyTorch

Implement the neural network in task 3 with PyTorch

In [ ]:
class FeedforwardNeuralNetworkRegressorPytorch(nn.Module):
    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_dims: List[int],
        depth: int,
        learning_rate: float,
        epochs: int
    ):
        super(FeedforwardNeuralNetworkRegressorPytorch, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.hidden_dims = hidden_dims
        self.depth = depth
        self.learning_rate = learning_rate
        self.epochs = epochs
        # Create list for all weights and biases
        # By using nn.Linear and activation function and nn.sequential module, define the neural network

        layer_sizes = [input_dim] + hidden_dims + [output_dim]
        layers = []




    def forward(self, x):



In [ ]:
np.random.seed(2023)

input_dim = X_train.shape[1]
output_dim = y_train.shape[1]
model = FeedforwardNeuralNetworkRegressorPytorch(input_dim, output_dim, [5], 1, 0.1, 100)

# Define the loss function and optimizer

# Training loop
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass


    # Backward pass and optimization


    # Print the loss for every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

y_pred = model(torch.from_numpy(X_test).to(torch.float32))
ytest = torch.from_numpy(y_test).to(torch.float32)
test_error = criterion(y_pred, ytest)
print("Test error:", test_error)

plt.figure()
plt.plot(train_error)
plt.show()